# PHP ve Apache içeren resmi bir Docker image'ını kullan
FROM php:8.1-apache

# PHP dosyalarını konteyner içindeki /var/www/html/ dizinine kopyala
COPY src/ /var/www/html/

# Apache'i başlat
CMD ["apache2-foreground"]
# PHP ve Apache içeren resmi bir Docker image'ını kullan

